# Site settings
title: 李强的博客
email: kata.Qlee@gmail.com
description: 天道酬勤

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://li-qiang.com" # the base hostname & protocol for your site
github_username:  li-qiang

encoding: "utf-8"

# Build settings
markdown: rdiscount

paginate: 6
paginate_path: "page:num"
